version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql2
    environment:
      MYSQL_DATABASE: inventory-service
      MYSQL_ROOT_PASSWORD: mysql1
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql-data:
